# CircleCI Configuration File

# version of circleci
version: 2

# set of jobs to run
jobs:
    spawn-from-api:
        docker:
            - image: riscvboom/riscvboom-images:0.0.12
        environment:
            JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
            TERM: dumb
        steps:
            - checkout
            - run:
                name: Create hash of toolchains
                command: |
                    .circleci/create-hash.sh
            - run:
                name: Create hash of toolchains
                command: |
                    echo "Hello world!"

# Order and dependencies of jobs to run
#workflows:
#    version: 2
#    build-and-test-boom-configs:
#        jobs:
#            # Make the toolchains
#            - install-riscv-toolchain
#            - install-esp-toolchain
#
#            # Build verilator
#            - prepare-build-environment
#
#            # Run generic syntax checking
#            - run-scala-checkstyle
#
#            # Prepare the verilator builds
#            - prepare-smallboomconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-riscv-toolchain
#            - prepare-mediumboomconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-riscv-toolchain
#            - prepare-largeboomconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-riscv-toolchain
#            - prepare-megaboomconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-riscv-toolchain
#            - prepare-smallboomandrocketconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-riscv-toolchain
#            - prepare-smallrv32boomconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-riscv-toolchain
#            - prepare-hwachaboomconfig:
#                requires:
#                    - prepare-build-environment
#                    - install-esp-toolchain
#
#            # Run the SmallBoomConfig tests
#            - smallboomconfig-run-csmith-tests:
#                requires:
#                    - prepare-smallboomconfig
#            - smallboomconfig-run-riscv-tests:
#                requires:
#                    - prepare-smallboomconfig
#
#            # Run the MediumBoomConfig tests
#            - mediumboomconfig-run-csmith-tests:
#                requires:
#                    - prepare-mediumboomconfig
#            - mediumboomconfig-run-riscv-tests:
#                requires:
#                    - prepare-mediumboomconfig
#
#            # Run the LargeBoomConfig tests
#            - largeboomconfig-run-csmith-tests:
#                requires:
#                    - prepare-largeboomconfig
#            - largeboomconfig-run-riscv-tests:
#                requires:
#                    - prepare-largeboomconfig
#
#            # Run the MegaBoomConfig tests
#            - megaboomconfig-run-csmith-tests:
#                requires:
#                    - prepare-megaboomconfig
#            - megaboomconfig-run-riscv-tests:
#                requires:
#                    - prepare-megaboomconfig
#
#            # Run the SmallBoomAndRocketConfig tests
#            - smallboomandrocketconfig-run-csmith-tests:
#                requires:
#                    - prepare-smallboomandrocketconfig
#            - smallboomandrocketconfig-run-riscv-tests:
#                requires:
#                    - prepare-smallboomandrocketconfig
#
#            # Run the SmallRV32BoomConfig tests
#            - smallrv32boomconfig-run-riscv-tests:
#                requires:
#                    - prepare-smallrv32boomconfig
#
#            # Run the HwachaBoomConfig tests
#            - hwachaboomconfig-run-riscv-tests:
#                requires:
#                    - prepare-hwachaboomconfig
