# CircleCI Configuration File

# version of circleci
version: 2

# set of jobs to run
jobs:
    spawn-from-api:
        docker:
            - image: riscvboom/riscvboom-images:0.0.12
        environment:
            JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
            TERM: dumb
        steps:
            - checkout
            - run:
                name: Create hash of toolchains
                command: |
                    .circleci/create-hash.sh
            - run:
                name: Create hash of toolchains
                command: |
                    exit 1

    hello:
        docker:
            - image: riscvboom/riscvboom-images:0.0.12
        environment:
            JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit
            TERM: dumb
        steps:
            - checkout
            - run:
                name: Create hash of toolchains
                command: |
                    .circleci/create-hash.sh
            - run:
                name: Create hash of toolchains
                command: |
                    echo "Hello world!"

# Order and dependencies of jobs to run
workflows:
    version: 2
    main-workflow:
        jobs:
            - hello
